name: fcar_lib
description: Flutter Clean Architecture project library.
version: 1.0.0+1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.8
  datadog_flutter_plugin: ^1.6.2
  device_info_plus: ^8.0.0
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  external_app_launcher: ^3.1.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  firebase_messaging: ^14.6.8
  firebase_remote_config: ^4.2.6
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^15.1.2
  flutter_native_splash: ^2.3.4
  flutter_secure_storage: ^8.1.0
  flutter_svg: ^2.0.7
  logger: ^2.0.2+1
  objectbox: ^2.3.0
  objectbox_flutter_libs: any
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # pull_to_refresh: ^2.0.0
  retry: ^3.1.0
  sentry_flutter: ^7.10.1
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.1.14
  video_compress: ^3.1.2
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  objectbox_generator: ^2.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
