name: fcar_lib
description: Flutter Clean Architecture project library.
version: 1.0.0+1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.8
  datadog_flutter_plugin: ^2.7.0
  device_info_plus: ^10.1.2
  dio: ^5.6.0
  dio_cache_interceptor: ^3.5.0
  external_app_launcher: ^4.0.0
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  firebase_remote_config: ^5.1.0
  flutter_appauth: ^7.0.0
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.7
  geolocator: ^12.0.0
  intl: ^0.19.0
  local_auth: ^2.3.0
  logger: ^2.0.2+1
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.0
  retry: ^3.1.2
  sentry_flutter: ^8.8.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.3.0
  video_compress: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  objectbox_generator: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
