// /// RemoteAuthModel is to keep the responses from Oauth server.
// ///
// /// [codeVerifier] and [nonce] generated by AppAuth when issuing the authorization request.
// /// Use this when exchanging the [authorizationCode] for a token.
// /// In [RemoteAuth.authWithNoCodeExchange] method.
// ///
// /// [idToken] returned by the authorization server.
// /// In [RemoteAuth.refreshToken] method.
// ///
// /// [authorizationCode] is the authorization code.
// /// In [RemoteAuth.refreshToken] method.
// ///
// /// [accessToken] and [refreshToken] returned by the authorization server.
// /// In [RemoteAuth.auth] and [RemoteAuth.refreshToken] methods.
// ///
// /// [accessTokenExpirationDateTime] indicates when [accessToken] will expire.
// /// In [RemoteAuth.auth] and [RemoteAuth.refreshToken] methods.
// ///
// /// [tokenAdditionalParameters] contains additional parameters returned by the authorization server
// ///   from making the token request.
// /// In [RemoteAuth.auth] and [RemoteAuth.refreshToken] methods.
// ///
// /// [authorizationAdditionalParameters] contains additional parameters returned by the authorization server
// ///   from making the authorization request.
// /// In [RemoteAuth.auth] and [RemoteAuth.authWithNoCodeExchange] methods.
// final class RemoteAuthModel {
//   String? codeVerifier;
//   String? nonce;
//   String? idToken;
//   String? authorizationCode;
//   String? refreshToken;
//   String? accessToken;
//   DateTime? accessTokenExpirationDateTime;
//   Map<String, dynamic>? tokenAdditionalParameters;
//   Map<String, dynamic>? authorizationAdditionalParameters;
// }
